moved files around

diff --git a/phakit b/phakit
--- a/phakit
+++ b/phakit
@@ -1,37 +1,51 @@
 #!/bin/bash
 
-# ──────────────────────────────────────────────────────────────────────────── #
-#                                    CONFIG                                    #
-# ──────────────────────────────────────────────────────────────────────────── #
-CONFIG_IMPORTED="0"
-if [ -f "config" ]; then
-    source "config"
-else
-    print "No config file found. Fetching latest from GitHub..."
-    source <(curl -s https://raw.githubusercontent.com/Darknetzz/phakit/main/config)
-fi
 
-if [ "$CONFIG_IMPORTED" -ne "1" ]; then
-    echo "Could not import config file."
-    exit 100
-fi
+# ──────────────────────────── SECTION: PRECHECKS ──────────────────────────── #
+LOCAL_APP_PATH="/usr/local/bin"
 
-
-
-# Make sure Python exists
-if ! command -v python3 &> /dev/null; then
-    echo "[ERROR] Python 3 is not installed."
+if [ ! -d "$LOCAL_APP_PATH" ]; then
+    echo "[ERROR] $LOCAL_APP_PATH does not exist. Exiting..."
     exit 1
 fi
+# ──────────────────────────── !SECTION /PRECHECKS ─────────────────────────── #
 
-# Check if pip packages are installed
-REQUIRED_PYTHON_PACKAGES=("subprocess" "argparse")
-for package in "${PACKAGES[@]}"; do
-    if ! python3 -c "import $package" &> /dev/null; then
-        echo "[ERROR] $package is not installed. Run 'pip install $package'."
-        exit 1
-    fi
-done
+
+
+
+# ──────────────────────────────────────────────────────────────────────────── #
+#                              SECTION: IMPORTS                                #
+# ──────────────────────────────────────────────────────────────────────────── #
+
+# ────────────────────────────── NOTE: FUNCTIONS ───────────────────────────── #
+FUNCTIONS_IMPORTED="0"
+source "$LOCAL_APP_PATH/linux/functions.bash" || exit 100
+
+if [ "$FUNCTIONS_IMPORTED" -ne "1" ]; then
+    echo "[ERROR] Could not import functions.bash file ($LOCAL_APP_PATH/linux/functions.bash). Exiting..."
+    exit 100
+else
+    print "[OK] Functions file imported." "SUCCESS"
+fi
+
+# ─────────────────────────────── NOTE: CONFIG ─────────────────────────────── #
+CONFIG_IMPORTED="0"
+source "$LOCAL_APP_PATH/linux/config.bash"
+
+if [ "$CONFIG_IMPORTED" -ne "1" ]; then
+    echo "[ERROR] Could not import functions.bash file ($LOCAL_APP_PATH/linux/functions.bash). Exiting..."
+    exit 100
+else
+    print "[OK] Config file imported." "SUCCESS"
+fi
+
+# ───────────────────────────── !SECTION /IMPORTS ──────────────────────────── #
+
+# Make sure Python exists
+if ! command -v "$PYTHON3" &> /dev/null; then
+    echo "[ERROR] Python 3 is not installed."
+    quit 101 "Python 3 is not installed."
+fi
 
 # REVIEW: Revies this conditional mess at some point...
 # Check if the script exists
